name: Surge.sh Preview

on:
  pull_request_target:
    # when using teardown: 'true', add default event types + closed event type
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Antora and the required extensions
        run: npm i antora

      - name: Generate Site
        run: npx antora antora-playbook.yml

      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: build/site
          failOnError: 'true'
          build: |
            echo Deploying to surge.sh

      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
